### ISSUE TITLE
Sometimes I get invalid CEN header (bad signature)

### ISSUE THREAD

**Issue by arfan** [sridharv/gojava#8]
I have created a simple hello world app using gojava, a java class that calls a go function https://github.com/arfan/experimentjava/ when I try to compile the java class sometimes I get error invalid CEN header (bad signature)

complete build script can be accessed here https://github.com/arfan/experimentjava/blob/master/runner.sh

here is the log

`$ ./runner.sh`

`Finished building hello.jar`

`error: error reading hello.jar; invalid CEN header (bad signature)`

`1 error`

`Exception in thread "main" java.lang.NoClassDefFoundError: go/hello/Hello`

 `       at JavaHello.main(JavaHello.java:5)`

`Caused by: java.lang.ClassNotFoundException: go.hello.Hello`

`       at java.net.URLClassLoader.findClass(URLClassLoader.java:381)`

`        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)`

`       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)`

`        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)`

`        ... 1 more`

But sometimes it also works like this:

`$ ./runner.sh`

`Finished building hello.jar`

`Hello World from java`

**Comment by sridharv** [comment]
Invalid CEN header usually shows up when you have a corrupted zip/jar file. Could you check to see if there is another process writing to the jar? Also, could you let me know what the sleep in the build script is for? If you're waiting for an external process to complete, there could be a race involved that is corrupting the jar.

**Comment by arfan** [comment]
Hi sridharv, 
Thank you for your reply, I think there is no other process writing to jar file, the sleep is basically useless, I just put it there to try whether it will work consistently if I put some delay in the script, but what I get is sometime it is work and sometime it does not work.

**Comment by sridharv** [comment]
When you get this error could you check to see the jar is an empty jar. Additionally, which OS are you running this on? I'll try and reproduce the error on my end.

**Comment by arfan** [comment]
Im using mac os high sierra. I have check it, the jar is not empty.

I think I have found the cause of this problem, if currently I already have hello.jar file in the same directory, the process of building the jar file seems to corrupt the jar somehow (the size will be different). but if I remove the hello.jar before building it. then it will be ok.

**Comment by sridharv** [comment]
Looks like the jar will need to be replaced atomically by writing it into a
temporary directory and then moving the file over. If you have the time to
make the change I'd be happy to accept a pull request. If not I'll try and
get the change in over the next couple of weeks.

Thanks!
Sridhar

**Comment by arfan** [comment]
Im not sure on how to do that, right now I make PR by deleting the jar file if it already exist.

**Comment by sridharv** [comment]
Thanks for taking the time for the pull request! I would like to fix it using an atomic replacement and so I'll push the change needed for it this weekend.
